"""VLABench external-asset resolution and LIBERO MJCF adaptation.

The VLABench asset repository is intentionally not vendored into LIBERO.  This
module keeps the source and asset revisions explicit, resolves files from a
user-provided download directory, and converts an individual VLABench MJCF
file into the small XML shape expected by robosuite's ``MujocoXMLObject``.

The converter is deliberately conservative:

* it never edits the downloaded asset tree;
* mesh and texture files are made absolute in the generated adapter XML, so
  robosuite can safely merge the object into a larger scene;
* VLABench's visual/collision groups (1/2 and 3 in the released bundle) are
  normalized to LIBERO's visual/collision groups (1 and 0); and
* a VLABench worldbody is wrapped in ``body/body[@name='object']`` when
  needed, which is the contract used by robosuite 1.4's XML object loader.

Only the small generated XML files are cached.  Meshes, textures, and other
large files remain in the external download directory.
"""

from __future__ import annotations

import copy
import getpass
import hashlib
import json
import math
import os
import re
import struct
import tempfile
import xml.etree.ElementTree as ET
import zlib
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Mapping, Tuple


VLABENCH_SOURCE_REPOSITORY = "OpenMOSS/VLABench"
VLABENCH_SOURCE_COMMIT = "cf588fe60c0c7282174fe979f5913170cfe69017"
VLABENCH_ASSET_REPOSITORY = "lerobot/vlabench-assets"
VLABENCH_ASSET_REVISION = "08d7a4479a55c8fbb89ac0fd6fcf06e53d65b4a4"
VLABENCH_ASSET_ROOT_ENV = "LIBERO_VLABENCH_ASSET_ROOT"
VLABENCH_ADAPTER_CACHE_ENV = "LIBERO_VLABENCH_ADAPTER_CACHE"
# Cache entries contain absolute external mesh / texture references.  Keep a
# schema component in the key so changing any normalization rule cannot reuse
# an adapter generated by an older converter.
# Bump when the generated XML contract changes.  Schema 11 includes the
# nested-default flattening from schema 9 and the flower footprint adapter,
# which scales mesh declarations / concrete transforms rather than emitting
# MuJoCo-invalid body ``scale`` attributes.  The flower scale itself is
# applied by the object wrapper after this cache key is resolved.
VLABENCH_CONVERTER_SCHEMA_VERSION = "11"

# Default to the colocated snapshot; other layouts can override this path.
DEFAULT_VLABENCH_ASSET_ROOT: Path | None = (
    Path(__file__).resolve().parents[4]
    / "dataset/libero_external_assets/vlabench_assets_08d7a447"
)

_MANIFEST_PATH = (
    Path(__file__).resolve().parents[1]
    / "assets"
    / "external"
    / "vlabench"
    / "manifest.json"
)


class VLABenchAssetError(RuntimeError):
    """Base class for adapter failures."""


class VLABenchAssetsUnavailable(VLABenchAssetError):
    """Raised when an external asset root or requested asset is unavailable."""


class VLABenchManifestError(VLABenchAssetError):
    """Raised when the committed manifest is malformed or unpinned."""


@dataclass(frozen=True)
class VLABenchAssetSpec:
    """A logical asset and its possible paths in the external repository.

    ``candidate_paths`` may contain ``Path.glob`` patterns.  This supports
    variant assets (for example ``tray/tray_*/model.xml``) without copying a
    directory listing into the LIBERO repository.
    """

    key: str
    category: str
    candidate_paths: tuple[str, ...]
    interactive: bool = False
    primitive_fallback: str | None = None
    notes: str = ""


def _as_path(value: str | os.PathLike[str] | None) -> Path | None:
    if value is None:
        return None
    return Path(value).expanduser()


def resolve_vlabench_asset_root(
    root: str | os.PathLike[str] | None = None,
    *,
    require_exists: bool = False,
) -> Path | None:
    """Resolve the user-downloaded VLABench asset directory.

    Resolution order is explicit ``root``, ``LIBERO_VLABENCH_ASSET_ROOT``,
    the compatibility variable ``VLABENCH_ASSET_ROOT``, then the colocated
    dataset snapshot. No download is performed.
    """

    candidates: list[Path] = []
    explicit = _as_path(root)
    if explicit is not None:
        # An explicit path is authoritative.  Falling through to a different
        # machine-local snapshot would make a typo silently select the wrong
        # revision.
        candidates.append(explicit)
    else:
        for env_name in (VLABENCH_ASSET_ROOT_ENV, "VLABENCH_ASSET_ROOT"):
            value = os.environ.get(env_name)
            if value:
                candidates.append(Path(value).expanduser())
                break
        if not candidates and DEFAULT_VLABENCH_ASSET_ROOT is not None:
            candidates.append(DEFAULT_VLABENCH_ASSET_ROOT)

    for candidate in candidates:
        resolved = candidate.resolve()
        if resolved.is_dir():
            return resolved

    if require_exists:
        searched = ", ".join(str(item) for item in candidates)
        raise VLABenchAssetsUnavailable(
            "VLABench assets are not downloaded. Set "
            f"{VLABENCH_ASSET_ROOT_ENV} to the root containing obj/; searched: {searched}"
        )
    return None


def load_vlabench_manifest(
    manifest_path: str | os.PathLike[str] | None = None,
) -> Mapping[str, Any]:
    """Load and validate the pinned, repository-owned asset manifest."""

    path = Path(manifest_path) if manifest_path is not None else _MANIFEST_PATH
    try:
        manifest = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise VLABenchManifestError(f"Unable to read VLABench manifest {path}: {exc}") from exc

    if not isinstance(manifest, dict):
        raise VLABenchManifestError("VLABench manifest must contain a JSON object")
    source = manifest.get("source")
    assets = manifest.get("assets")
    entries = manifest.get("entries")
    if not isinstance(source, dict) or not isinstance(assets, dict) or not isinstance(entries, list):
        raise VLABenchManifestError("Manifest requires source, assets, and entries fields")
    if source.get("commit") != VLABENCH_SOURCE_COMMIT:
        raise VLABenchManifestError(
            "Manifest source commit is not pinned to " f"{VLABENCH_SOURCE_COMMIT}"
        )
    if assets.get("revision") != VLABENCH_ASSET_REVISION:
        raise VLABenchManifestError(
            "Manifest asset revision is not pinned to " f"{VLABENCH_ASSET_REVISION}"
        )
    if assets.get("repository") != VLABENCH_ASSET_REPOSITORY:
        raise VLABenchManifestError("Manifest asset repository is unexpected")

    seen: set[str] = set()
    for entry in entries:
        if not isinstance(entry, dict):
            raise VLABenchManifestError("Every manifest entry must be an object")
        key = entry.get("key")
        candidates = entry.get("candidate_paths")
        if not isinstance(key, str) or not key or key in seen:
            raise VLABenchManifestError(f"Invalid or duplicate manifest key: {key!r}")
        if not isinstance(candidates, list) or not candidates or not all(
            isinstance(candidate, str)
            and candidate
            and not Path(candidate).is_absolute()
            and ".." not in Path(candidate).parts
            for candidate in candidates
        ):
            raise VLABenchManifestError(f"Invalid candidate paths for {key!r}")
        seen.add(key)
    return manifest


def iter_vlabench_asset_specs(
    category: str | None = None,
    *,
    manifest_path: str | os.PathLike[str] | None = None,
) -> tuple[VLABenchAssetSpec, ...]:
    """Return manifest entries, optionally filtered by category."""

    manifest = load_vlabench_manifest(manifest_path)
    specs: list[VLABenchAssetSpec] = []
    for entry in manifest["entries"]:
        entry_category = str(entry.get("category", "other"))
        if category is not None and entry_category != category:
            continue
        specs.append(
            VLABenchAssetSpec(
                key=str(entry["key"]),
                category=entry_category,
                candidate_paths=tuple(str(item) for item in entry["candidate_paths"]),
                interactive=bool(entry.get("interactive", False)),
                primitive_fallback=entry.get("primitive_fallback"),
                notes=str(entry.get("notes", "")),
            )
        )
    return tuple(specs)


def get_vlabench_asset_spec(
    key: str,
    *,
    manifest_path: str | os.PathLike[str] | None = None,
) -> VLABenchAssetSpec:
    """Look up one logical asset by key."""

    normalized = key.lower()
    for spec in iter_vlabench_asset_specs(manifest_path=manifest_path):
        if spec.key.lower() == normalized:
            return spec
    raise VLABenchAssetsUnavailable(f"Unknown VLABench asset key: {key!r}")


def _safe_relative_candidate(root: Path, candidate: str) -> Path:
    candidate_path = Path(candidate)
    if candidate_path.is_absolute() or ".." in candidate_path.parts:
        raise VLABenchManifestError(f"Asset candidate escapes external root: {candidate!r}")
    return root / candidate_path


def _candidate_matches(root: Path, candidate: str) -> Iterable[Path]:
    path = _safe_relative_candidate(root, candidate)
    if any(char in candidate for char in "*?["):
        # Path.glob handles wildcards in any component (not only the final
        # filename), which is needed for variant directories such as
        # ``tray/tray_*/model.xml``.
        yield from sorted(root.glob(candidate))
    elif path.is_file():
        yield path


def _token_fallback_matches(root: Path, spec: VLABenchAssetSpec) -> Iterable[Path]:
    """Find a known logical name in alternate archive layouts.

    This fallback is intentionally restricted to the ``obj/meshes`` subtree
    and exact path-component/name tokens.  It is useful while the upstream
    download is still being populated, and cannot escape the configured root.
    """

    key_tokens = [token for token in re.split(r"[^a-z0-9]+", spec.key.lower()) if token]
    if not key_tokens:
        return
    meshes_root = root / "obj" / "meshes"
    if not meshes_root.is_dir():
        return
    for xml_path in sorted(meshes_root.rglob("*.xml")):
        haystack = "/".join(part.lower() for part in xml_path.relative_to(meshes_root).parts)
        if all(token in haystack for token in key_tokens):
            yield xml_path


def resolve_vlabench_asset(
    key: str,
    root: str | os.PathLike[str] | None = None,
    *,
    require: bool = True,
    manifest_path: str | os.PathLike[str] | None = None,
) -> Path | None:
    """Resolve a manifest key to one downloaded MJCF/XML file."""

    spec = get_vlabench_asset_spec(key, manifest_path=manifest_path)
    asset_root = resolve_vlabench_asset_root(root, require_exists=require)
    if asset_root is None:
        return None

    attempts: list[str] = []
    for candidate in spec.candidate_paths:
        attempts.append(candidate)
        for match in _candidate_matches(asset_root, candidate):
            return match.resolve()
    for match in _token_fallback_matches(asset_root, spec):
        return match.resolve()
    if require:
        raise VLABenchAssetsUnavailable(
            f"Asset {key!r} is not present below {asset_root}; candidates: {attempts}"
        )
    return None


def _resolve_resource_file(xml_path: Path, file_value: str) -> Path:
    candidate = Path(file_value)
    return candidate if candidate.is_absolute() else (xml_path.parent / candidate).resolve()


def referenced_vlabench_files(xml_path: str | os.PathLike[str]) -> tuple[Path, ...]:
    """Return all file references in a VLABench XML (without checking them)."""

    path = Path(xml_path).resolve()
    try:
        root = ET.parse(path).getroot()
    except (OSError, ET.ParseError) as exc:
        raise VLABenchAssetError(f"Unable to parse VLABench XML {path}: {exc}") from exc
    references: list[Path] = []
    for element in root.iter():
        value = element.get("file")
        if value:
            references.append(_resolve_resource_file(path, value))
    return tuple(references)


def validate_vlabench_xml_resources(
    xml_path: str | os.PathLike[str],
) -> tuple[Path, ...]:
    """Return missing files referenced by an XML asset."""

    return tuple(path for path in referenced_vlabench_files(xml_path) if not path.is_file())


def audit_vlabench_assets(
    root: str | os.PathLike[str] | None = None,
    *,
    category: str | None = None,
    manifest_path: str | os.PathLike[str] | None = None,
) -> list[dict[str, Any]]:
    """Produce machine-readable availability/resource status for each entry."""

    asset_root = resolve_vlabench_asset_root(root, require_exists=False)
    result: list[dict[str, Any]] = []
    for spec in iter_vlabench_asset_specs(category, manifest_path=manifest_path):
        entry: dict[str, Any] = {
            "key": spec.key,
            "category": spec.category,
            "interactive": spec.interactive,
            "available": False,
            "xml": None,
            "missing_resources": [],
        }
        if asset_root is not None:
            path = resolve_vlabench_asset(
                spec.key,
                asset_root,
                require=False,
                manifest_path=manifest_path,
            )
            if path is not None:
                missing = validate_vlabench_xml_resources(path)
                entry.update(
                    {
                        "available": not missing,
                        "xml": str(path),
                        "missing_resources": [str(item) for item in missing],
                    }
                )
        result.append(entry)
    return result


def _flatten_nested_default_classes(root: ET.Element) -> None:
    """Lift nested MJCF default classes into robosuite's flat contract.

    VLABench flower XMLs place a ``grasppoint`` site default below the
    ``collision`` default.  MuJoCo accepts that hierarchy, but robosuite's
    ``MujocoXML`` loader only indexes direct children of the top-level
    ``<default>`` element and consequently raises ``KeyError`` while
    inlining ``class="grasppoint"``.  The converter owns a deep copy of the
    source tree, so lifting those class declarations is safe and leaves the
    pinned download untouched.
    """

    defaults = root.find("default")
    if defaults is None:
        return

    lifted: list[ET.Element] = []

    def visit(parent: ET.Element, *, top_level: bool = False) -> None:
        for child in list(parent):
            if child.tag != "default":
                continue
            visit(child)
            if not top_level and child.get("class"):
                parent.remove(child)
                lifted.append(child)

    visit(defaults, top_level=True)
    for child in lifted:
        defaults.append(child)


def _normalise_geom_groups(root: ET.Element) -> None:
    """Map VLABench visual/collision groups into robosuite's groups."""

    default_classes = root.find("default")
    if default_classes is not None:
        for default in default_classes.findall("default"):
            class_name = default.get("class")
            geom = default.find("geom")
            if geom is None:
                continue
            if class_name == "visual":
                geom.set("group", "1")
                geom.set("contype", geom.get("contype", "0"))
                geom.set("conaffinity", geom.get("conaffinity", "0"))
            elif class_name == "collision":
                geom.set("group", "0")

    for geom in root.iter("geom"):
        class_name = geom.get("class")
        group = geom.get("group")
        if group == "2":
            geom.set("group", "1")
        elif group == "3":
            geom.set("group", "0")
        elif group is None:
            # A mesh without an explicit class is a visual geom in the
            # released VLABench objects (for example cart); primitive geoms
            # without a class are safer as collision geometry.
            geom.set("group", "1" if geom.get("type", "") == "mesh" else "0")
        if class_name == "visual":
            geom.set("group", "1")
            geom.set("contype", geom.get("contype", "0"))
            geom.set("conaffinity", geom.get("conaffinity", "0"))
        elif class_name == "collision":
            geom.set("group", "0")


def _absolutise_asset_files(root: ET.Element, source_dir: Path) -> None:
    asset = root.find("asset")
    if asset is None:
        return
    for element in asset.iter():
        file_value = element.get("file")
        if not file_value:
            continue
        path = Path(file_value)
        if not path.is_absolute():
            path = (source_dir / path).resolve()
        element.set("file", str(path))


def _remove_unreferenced_mesh_assets(root: ET.Element) -> None:
    """Drop mesh declarations that no concrete geom uses.

    MuJoCo versions differ in how strictly they validate an unused mesh.  A
    pinned VLABench table contains a planar, unnamed OBJ that is declared in
    ``asset`` but is not referenced by any geom; naming it during adaptation
    makes some versions validate its zero volume and fail compilation.  The
    generated adapter may safely omit such declarations.  References from
    default geom templates count as real references, and unnamed meshes are
    retained when a geom uses their file stem (the convention handled by
    ``_ensure_named_meshes`` below).
    """

    asset = root.find("asset")
    if asset is None:
        return
    mesh_references = {
        str(geom.get("mesh"))
        for geom in root.iter("geom")
        if geom.get("mesh")
    }
    for mesh in list(asset.findall("mesh")):
        mesh_name = mesh.get("name")
        if mesh_name:
            referenced = mesh_name in mesh_references
        else:
            file_value = mesh.get("file", "")
            stem = Path(file_value).stem
            referenced = bool(
                stem
                and (stem in mesh_references or Path(file_value).name in mesh_references)
            )
        if not referenced:
            asset.remove(mesh)


def _ensure_named_meshes(root: ET.Element) -> None:
    """Give unnamed mesh assets stable names when a geom refers to a stem."""

    asset = root.find("asset")
    if asset is None:
        return
    mesh_name_by_stem: dict[str, str] = {}
    used_names = {
        str(mesh.get("name")) for mesh in asset.findall("mesh") if mesh.get("name")
    }
    for index, mesh in enumerate(asset.findall("mesh")):
        if mesh.get("name"):
            continue
        file_name = mesh.get("file", "mesh")
        stem = Path(file_name).stem
        generated = re.sub(r"[^A-Za-z0-9_]+", "_", stem) or f"mesh_{index}"
        if generated[0].isdigit():
            generated = f"mesh_{generated}"
        generated = f"{generated}_{index}"
        suffix = 1
        while generated in used_names:
            generated = f"{generated}_{suffix}"
            suffix += 1
        mesh.set("name", generated)
        used_names.add(generated)
        mesh_name_by_stem.setdefault(stem, generated)
    if not mesh_name_by_stem:
        return
    for geom in root.iter("geom"):
        mesh = geom.get("mesh")
        if mesh in mesh_name_by_stem:
            geom.set("mesh", mesh_name_by_stem[mesh])


def _ensure_named_sites_and_joints(root: ET.Element) -> None:
    """Give unnamed MJCF elements stable names for robosuite bookkeeping."""

    def concrete_elements(tag: str) -> list[ET.Element]:
        """Return concrete XML elements, excluding ``default`` templates.

        MuJoCo's ``default`` subtree contains attribute templates.  A
        template ``<site>`` does not accept a concrete ``name`` attribute in
        all supported MuJoCo releases, and naming it also mutates the source
        semantics.  Only elements in the worldbody (or another concrete
        subtree) need names for robosuite bookkeeping.
        """

        result: list[ET.Element] = []

        def visit(element: ET.Element, in_default: bool = False) -> None:
            in_default = in_default or element.tag == "default"
            if element.tag == tag and not in_default:
                result.append(element)
            for child in element:
                visit(child, in_default)

        visit(root)
        return result

    for tag, prefix in (("site", "site"), ("joint", "joint"), ("body", "body")):
        elements = concrete_elements(tag)
        used_names = {
            str(element.get("name")) for element in elements if element.get("name")
        }
        for index, element in enumerate(elements):
            if not element.get("name"):
                generated = f"{prefix}_{index}"
                suffix = 1
                while generated in used_names:
                    generated = f"{prefix}_{index}_{suffix}"
                    suffix += 1
                element.set("name", generated)
                used_names.add(generated)
    # Nested object XML is merged into LIBERO's parent MJCF, so compiler
    # attributes are not always retained by robosuite's object serializer.
    # Make ranged hinge/slide limits explicit on the concrete joint itself;
    # this is semantically identical to ``autolimits=true`` and supports
    # MuJoCo 2.x and 3.x loaders alike.
    for joint in concrete_elements("joint"):
        if joint.get("range") is not None and joint.get("limited") is None:
            joint.set("limited", "true")


def _ensure_named_geoms(root: ET.Element) -> None:
    """Name concrete worldbody geoms for instance segmentation bookkeeping.

    MuJoCo accepts unnamed geoms, but robosuite's ``instances_to_ids`` is
    built from named geometry groups.  The complete VLABench hammer assembly
    is a useful example: its visual and two collision geoms render in RGB,
    yet an unnamed geometry set produced no asset pixels in the processed
    instance mask.  Defaults are templates rather than concrete geoms and are
    intentionally skipped.
    """

    worldbody = root.find("worldbody")
    if worldbody is None:
        return
    used_names = {
        str(geom.get("name"))
        for geom in worldbody.iter("geom")
        if geom.get("name")
    }
    next_index = 0
    for geom in worldbody.iter("geom"):
        if geom.get("name"):
            continue
        while f"geom_{next_index}" in used_names:
            next_index += 1
        name = f"geom_{next_index}"
        geom.set("name", name)
        used_names.add(name)
        next_index += 1


_NAMETAG_FONT = {
    "A": ("01110", "10001", "10001", "11111", "10001", "10001", "10001"),
    "C": ("01111", "10000", "10000", "10000", "10000", "10000", "01111"),
    "E": ("11111", "10000", "10000", "11110", "10000", "10000", "11111"),
    "H": ("10001", "10001", "10001", "11111", "10001", "10001", "10001"),
    "O": ("01110", "10001", "10001", "10001", "10001", "10001", "01110"),
    "S": ("01111", "10000", "10000", "01110", "00001", "00001", "11110"),
    "T": ("11111", "00100", "00100", "00100", "00100", "00100", "00100"),
    "U": ("10001", "10001", "10001", "10001", "10001", "10001", "01110"),
}


def _nametag_png_chunk(kind: bytes, payload: bytes) -> bytes:
    return struct.pack(">I", len(payload)) + kind + payload + struct.pack(
        ">I", zlib.crc32(kind + payload) & 0xFFFFFFFF
    )


def _ensure_hotsauce_nametag_texture() -> Path:
    """Create the tiny repo-owned Hot Sauce presentation texture on demand.

    VLABench ships ingredient textures only for its two shaker NameTags.  The
    hotsauce bottle has its own package texture, but a same-spec detached tag
    needs a compact, camera-readable label.  Generate that visual support
    asset in the private adapter cache so no external asset tree is modified.
    """

    destination = _default_adapter_cache_dir() / "hotsauce-nametag-v2.png"
    if destination.is_file():
        return destination
    text = "HOT SAUCE"
    scale = 4
    glyph_width = 5
    spacing = 1
    text_width = sum(
        (3 if character == " " else glyph_width) + spacing for character in text
    ) * scale - spacing * scale
    width, height = 300, 100
    background = (248, 248, 248)
    ink = (45, 104, 164)
    border = (224, 190, 180)
    pixels = [[background for _ in range(width)] for _ in range(height)]
    for x in range(width):
        for y in (2, 3, height - 4, height - 3):
            pixels[y][x] = border
    for y in range(height):
        for x in (2, 3, width - 4, width - 3):
            pixels[y][x] = border
    origin_x = (width - text_width) // 2
    origin_y = (height - 7 * scale) // 2
    cursor_x = origin_x
    for character in text:
        glyph = _NAMETAG_FONT.get(character)
        glyph_width_for_text = 3 if character == " " else glyph_width
        if glyph is not None:
            for row, bits in enumerate(glyph):
                for column, bit in enumerate(bits):
                    if bit == "1":
                        for dy in range(scale):
                            for dx in range(scale):
                                pixels[origin_y + row * scale + dy][
                                    cursor_x + column * scale + dx
                                ] = ink
        cursor_x += (glyph_width_for_text + spacing) * scale
    raw = b"".join(
        b"\x00" + b"".join(bytes(pixel) for pixel in row) for row in pixels
    )
    png = b"\x89PNG\r\n\x1a\n" + _nametag_png_chunk(
        b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    ) + _nametag_png_chunk(b"IDAT", zlib.compress(raw, 9)) + _nametag_png_chunk(
        b"IEND", b""
    )
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_suffix(f".{os.getpid()}.tmp")
    temporary.write_bytes(png)
    os.replace(temporary, destination)
    return destination


def _find_nametag_assets(source: Path, content: str) -> tuple[Path, Path] | None:
    """Resolve VLABench's ordinary label mesh and texture.

    The upstream ``NameTag`` entity uses this small package-label mesh with a
    normal ingredient texture (for example ``sugar.png``).  It lives beside
    the condiment assets in the external bundle, so walk only the bounded
    parent chain of the selected XML rather than searching the filesystem.

    VLABench's add-condiment task ships ingredient textures for the two shaker
    ingredients.  LIBERO adds a matching generated presentation texture for
    hot sauce; it remains visual-only and is cached outside the asset bundle.
    The chemistry rearrangement adapter uses the same source NameTag mesh with
    the released solution textures.  These labels are visual support attached
    to the static rack, not BDDL objects or evaluator state.
    """

    safe_content = re.sub(r"[^A-Za-z0-9_-]+", "", str(content)).lower()
    if safe_content not in {"sugar", "salt", "hotsauce", "cuso4", "cucl2", "kmno4"}:
        raise VLABenchAssetError(
            f"Unsupported VLABench visual tag {content!r}; expected an ingredient or chemistry solution"
        )
    for ancestor in (source.parent, *source.parents):
        meshes_root = ancestor / "obj" / "meshes"
        if meshes_root.is_dir():
            tag_root = meshes_root / "tube" / "nametag"
            mesh_path = tag_root / "name.obj"
            if safe_content == "hotsauce":
                texture_path = _ensure_hotsauce_nametag_texture()
            elif safe_content in {"cuso4", "cucl2", "kmno4"}:
                texture_path = tag_root / "solution" / f"{safe_content}.png"
            else:
                texture_path = tag_root / "ingredient" / f"{safe_content}.png"
            if mesh_path.is_file() and texture_path.is_file():
                return mesh_path.resolve(), texture_path.resolve()
    return None


def _add_visual_tag(root: ET.Element, source: Path, content: str | None) -> None:
    """Attach a normal VLABench package label to a condiment object.

    This is intentionally visual-only: the label is part of the external
    asset's ordinary packaging and has no joint, contact, or evaluator role.
    The resulting object remains one movable condiment with the same free
    joint and terminal predicate as an unlabelled variant.  The presentation
    plate uses two back-to-back visual geoms so its print is readable from
    either side without making the world-frame body camera-dependent.
    """

    if content is None:
        return
    assets = _find_nametag_assets(source, content)
    if assets is None:
        raise VLABenchAssetsUnavailable(
            "VLABench condiment labels require obj/meshes/tube/nametag/name.obj "
            f"and ingredient/{content}.png in the pinned asset bundle"
        )
    mesh_path, texture_path = assets
    asset = root.find("asset")
    if asset is None:
        asset = ET.SubElement(root, "asset")
    token = re.sub(r"[^A-Za-z0-9_]+", "_", str(content).lower())
    mesh_name = f"vlabench_{token}_label_mesh"
    texture_name = f"vlabench_{token}_label_texture"
    material_name = f"vlabench_{token}_label_material"
    ET.SubElement(
        asset,
        "mesh",
        {
            "name": mesh_name,
            "file": str(mesh_path),
            # The source NameTag mesh is authored at 0.03.  Upstream
            # add_condiment_series.py applies ``scale=2`` to the entity;
            # baking that presentation multiplier into the XML keeps the
            # label legible in LIBERO's renderer without adding a semantic
            # object or segmentation channel. Keep the source mesh handedness
            # so the public OpenCV-row observation reads the texture normally.
            "scale": "0.06 0.06 0.06",
        },
    )
    ET.SubElement(
        asset,
        "texture",
        {
            "name": texture_name,
            "type": "2d",
            "file": str(texture_path),
        },
    )
    ET.SubElement(
        asset,
        "material",
        {"name": material_name, "texture": texture_name},
    )

    worldbody = root.find("worldbody")
    if worldbody is None:
        worldbody = ET.SubElement(root, "worldbody")
    target_body = worldbody.find("./body")
    if target_body is None:
        target_body = ET.SubElement(worldbody, "body", {"name": "object"})
    tag_body = ET.SubElement(
        target_body,
        "body",
        {
            "name": f"vlabench_{token}_label",
            # Match the upstream NameTag pose: it is spawned 0.1 m in front
            # of the parent and 0.1 m below its frame.  Keeping this pose
            # explicit also makes the presentation stable when the source
            # XML has nested transforms.
            "pos": "0.1 0 -0.1",
            "euler": "0 1.57079632679 1.57079632679",
        },
    )
    # NameTag is a thin printed plate.  Keep the original texture-bearing
    # face for the front, then place a second visual-only copy back-to-back.
    # Rotating the copy around the local vertical (source-X) axis preserves
    # the upright, non-mirrored print when it is viewed from the opposite
    # side.  The tiny rear offset makes the two physical faces deterministic
    # in the depth buffer while retaining the source plate thickness.
    visual_attributes = {
        "type": "mesh",
        "mesh": mesh_name,
        "material": material_name,
        "group": "1",
        "contype": "0",
        "conaffinity": "0",
    }
    ET.SubElement(
        tag_body,
        "geom",
        {"name": f"vlabench_{token}_label_geom", **visual_attributes},
    )
    ET.SubElement(
        tag_body,
        "geom",
        {
            "name": f"vlabench_{token}_label_back_geom",
            "pos": "0 -0.00005 0",
            # Quaternion form is independent of the source XML's compiler
            # angle setting (the pinned condiment XMLs use the MJCF default
            # degree convention, while the standalone NameTag uses radians).
            "quat": "0 1 0 0",
            **visual_attributes,
        },
    )


def _set_visual_rgba(root: ET.Element, rgba: Iterable[float] | None) -> None:
    """Override a ChemistryTube solution colour without touching collisions."""

    if rgba is None:
        return
    values = tuple(float(value) for value in rgba)
    if len(values) != 4 or any(not math.isfinite(value) for value in values):
        raise VLABenchAssetError(
            f"visual_rgba must contain four finite values, got {rgba!r}"
        )
    if any(value < 0.0 or value > 1.0 for value in values):
        raise VLABenchAssetError(
            f"visual_rgba values must lie in [0, 1], got {values!r}"
        )
    material = root.find("./asset/material[@name='CaSO4']")
    if material is None:
        raise VLABenchAssetError(
            "visual_rgba requested for an asset without the ChemistryTube "
            "CaSO4 solution material"
        )
    material.set("rgba", " ".join(f"{value:.8g}" for value in values))


def _default_geom_attributes(root: ET.Element) -> dict[str, dict[str, str]]:
    """Collect effective geom attributes for the XML default classes.

    ``MujocoXML`` expands these templates before the object is merged into a
    task.  The adapter needs the same mass/density view to identify a truly
    massless dynamic body, while keeping the templates themselves unchanged.
    """

    defaults = root.find("./default")
    if defaults is None:
        return {}

    result: dict[str, dict[str, str]] = {"": {}}
    root_geom = defaults.find("./geom")
    if root_geom is not None:
        result[""] = dict(root_geom.attrib)

    def visit(default: ET.Element, inherited: Mapping[str, str]) -> None:
        effective = dict(inherited)
        geom = default.find("./geom")
        if geom is not None:
            effective.update(geom.attrib)
        class_name = default.get("class")
        if class_name:
            result[class_name] = effective
        for child in default.findall("./default"):
            visit(child, effective)

    for child in defaults.findall("./default"):
        visit(child, result[""])
    return result


def _effective_geom_attribute(
    geom: ET.Element,
    attribute: str,
    defaults: Mapping[str, Mapping[str, str]],
) -> str | None:
    value = geom.get(attribute)
    if value is not None:
        return value
    class_name = geom.get("class")
    if class_name and class_name in defaults:
        value = defaults[class_name].get(attribute)
        if value is not None:
            return value
    return defaults.get("", {}).get(attribute)


def _geom_has_nonzero_volume(
    geom: ET.Element,
    defaults: Mapping[str, Mapping[str, str]],
) -> bool:
    """Conservatively determine whether a density-derived geom has volume."""

    geom_type = _effective_geom_attribute(geom, "type", defaults) or "box"
    size_value = _effective_geom_attribute(geom, "size", defaults)
    try:
        size = [float(value) for value in (size_value or "").replace(",", " ").split()]
    except ValueError:
        return False
    if geom_type == "sphere":
        return bool(size and size[0] > 0)
    if geom_type in {"cylinder", "capsule"}:
        return bool(len(size) >= 2 and size[0] > 0 and size[1] > 0)
    if geom_type == "box":
        return bool(len(size) >= 3 and all(value > 0 for value in size[:3]))
    # A mesh may be watertight or shell-like; the actual compiler is the
    # authority for unusual binary formats.  Do not call it massless merely
    # because its bounds are unavailable here.
    return geom_type == "mesh"


def _geom_has_positive_mass(
    geom: ET.Element,
    defaults: Mapping[str, Mapping[str, str]],
) -> bool:
    """Check concrete/default mass semantics without changing either one."""

    mass_value = _effective_geom_attribute(geom, "mass", defaults)
    if mass_value is not None:
        try:
            mass = float(mass_value)
        except ValueError:
            return False
        # MuJoCo's explicit mass=0 suppresses density-derived mass, including
        # when density is also present on the concrete geom.
        return mass > 0

    density_value = _effective_geom_attribute(geom, "density", defaults)
    if density_value is None:
        # MuJoCo's built-in positive density applies when no mass or density
        # override is present, provided the geometry has nonzero extent.
        return _geom_has_nonzero_volume(geom, defaults)
    try:
        return float(density_value) > 0 and _geom_has_nonzero_volume(geom, defaults)
    except ValueError:
        return False


def _iter_concrete_bodies(worldbody: ET.Element) -> Iterable[ET.Element]:
    def visit(body: ET.Element) -> Iterable[ET.Element]:
        yield body
        for child in body.findall("./body"):
            yield from visit(child)

    for body in worldbody.findall("./body"):
        yield from visit(body)


def _body_has_positive_mass(
    body: ET.Element,
    defaults: Mapping[str, Mapping[str, str]],
) -> bool:
    inertial = body.find("./inertial")
    if inertial is not None:
        try:
            if float(inertial.get("mass", "0")) > 0:
                return True
        except ValueError:
            pass

    collision_geoms = [geom for geom in body.findall("./geom") if geom.get("group") == "0"]
    if collision_geoms:
        # A body with its own collision geoms still needs positive mass even
        # when a nested drawer / link has an inertial element.  MuJoCo's
        # ``inertiagrouprange`` validation checks this body's concrete geoms;
        # do not let child mass hide a massless parent collision shell.
        return any(_geom_has_positive_mass(geom, defaults) for geom in collision_geoms)
    elif any(_geom_has_positive_mass(geom, defaults) for geom in body.findall("./geom")):
        # A visual-only body has no collision proxy to receive a repair.  Its
        # explicit positive geometry mass is still useful evidence that it is
        # not massless.
        return True

    # A parent with a joint can derive mass and inertia from nested bodies.
    return any(_body_has_positive_mass(child, defaults) for child in body.findall("./body"))


def _ensure_positive_dynamic_body_mass(
    root: ET.Element,
    *,
    include_static_bodies: bool = False,
) -> None:
    """Repair only bodies that are actually dynamic and massless.

    Several VLABench XMLs intentionally define collision templates with
    ``mass=0`` because they are static fixtures.  LIBERO's object wrapper
    adds a free joint to movable objects, and source articulated child bodies
    can also have hinge/slide joints.  For those bodies only, add a small
    explicit mass to one *concrete* collision geom.  A fixture may explicitly
    opt into ``include_static_bodies`` when LIBERO's task compiler requires
    mass on otherwise fixed child bodies; that mode still touches only
    concrete geoms.  Default templates and every other attribute remain
    untouched, so density/mass semantics are not globally rewritten.
    """

    worldbody = root.find("./worldbody")
    if worldbody is None:
        return
    defaults = _default_geom_attributes(root)
    object_body = worldbody.find("./body/body[@name='object']")
    for body in _iter_concrete_bodies(worldbody):
        has_direct_joint = bool(body.findall("./joint"))
        is_movable_root = body is object_body
        if not include_static_bodies and not has_direct_joint and not is_movable_root:
            continue
        if _body_has_positive_mass(body, defaults):
            continue
        collision_geoms = [geom for geom in body.findall("./geom") if geom.get("group") == "0"]
        target = collision_geoms[0] if collision_geoms else next(iter(body.findall("./geom")), None)
        if target is not None:
            target.set("mass", "0.1")


def _vec3(value: str | None, default: tuple[float, float, float] = (0.0, 0.0, 0.0)) -> tuple[float, float, float]:
    if not value:
        return default
    try:
        values = [float(part) for part in value.replace(",", " ").split()]
    except ValueError:
        return default
    if len(values) < 3:
        return default
    return values[:3]


# ``libero``'s pinned simulation environment still supports Python 3.8.
# Keep these runtime aliases compatible with it (``from __future__ import
# annotations`` does not defer subscription in a module-level assignment).
_Matrix3 = Tuple[Tuple[float, float, float], ...]
_Vector3 = Tuple[float, float, float]
_Transform = Tuple[_Matrix3, _Vector3]

_IDENTITY_MATRIX: _Matrix3 = (
    (1.0, 0.0, 0.0),
    (0.0, 1.0, 0.0),
    (0.0, 0.0, 1.0),
)


def _matrix_vector(matrix: _Matrix3, vector: _Vector3) -> _Vector3:
    return tuple(
        sum(matrix[row][column] * vector[column] for column in range(3))
        for row in range(3)
    )  # type: ignore[return-value]


def _matrix_multiply(left: _Matrix3, right: _Matrix3) -> _Matrix3:
    return tuple(
        tuple(
            sum(left[row][index] * right[index][column] for index in range(3))
            for column in range(3)
        )
        for row in range(3)
    )  # type: ignore[return-value]


def _matrix_transpose(matrix: _Matrix3) -> _Matrix3:
    return tuple(
        tuple(matrix[column][row] for column in range(3)) for row in range(3)
    )  # type: ignore[return-value]


def _compose_transform(parent: _Transform, local: _Transform) -> _Transform:
    """Compose a child MJCF transform with its parent transform.

    The pair is ``(rotation, translation)`` and maps a point in the local
    frame to the frame in which ``parent`` is expressed.  Keeping this small
    representation local to the adapter avoids introducing a runtime numpy
    dependency just to move a handful of placement sites.
    """

    parent_rotation, parent_translation = parent
    local_rotation, local_translation = local
    rotation = _matrix_multiply(parent_rotation, local_rotation)
    translated = _matrix_vector(parent_rotation, local_translation)
    translation = tuple(
        parent_translation[index] + translated[index] for index in range(3)
    )
    return rotation, translation  # type: ignore[return-value]


def _transform_point(transform: _Transform, point: _Vector3) -> _Vector3:
    rotation, translation = transform
    rotated = _matrix_vector(rotation, point)
    return tuple(translation[index] + rotated[index] for index in range(3))  # type: ignore[return-value]


def _inverse_transform_point(transform: _Transform, point: _Vector3) -> _Vector3:
    rotation, translation = transform
    relative = tuple(point[index] - translation[index] for index in range(3))
    return _matrix_vector(_matrix_transpose(rotation), relative)


def _normalise_vector(vector: _Vector3) -> _Vector3 | None:
    norm = math.sqrt(sum(value * value for value in vector))
    if norm <= 1e-12:
        return None
    return tuple(value / norm for value in vector)  # type: ignore[return-value]


def _axis_rotation(axis: str, angle: float) -> _Matrix3:
    cosine = math.cos(angle)
    sine = math.sin(angle)
    if axis == "x":
        return (
            (1.0, 0.0, 0.0),
            (0.0, cosine, -sine),
            (0.0, sine, cosine),
        )
    if axis == "y":
        return (
            (cosine, 0.0, sine),
            (0.0, 1.0, 0.0),
            (-sine, 0.0, cosine),
        )
    return (
        (cosine, -sine, 0.0),
        (sine, cosine, 0.0),
        (0.0, 0.0, 1.0),
    )


def _quat_rotation(values: list[float]) -> _Matrix3:
    if len(values) < 4:
        return _IDENTITY_MATRIX
    norm = math.sqrt(sum(value * value for value in values[:4]))
    if norm <= 1e-12:
        return _IDENTITY_MATRIX
    w, x, y, z = (value / norm for value in values[:4])
    return (
        (1.0 - 2.0 * (y * y + z * z), 2.0 * (x * y - z * w), 2.0 * (x * z + y * w)),
        (2.0 * (x * y + z * w), 1.0 - 2.0 * (x * x + z * z), 2.0 * (y * z - x * w)),
        (2.0 * (x * z - y * w), 2.0 * (y * z + x * w), 1.0 - 2.0 * (x * x + y * y)),
    )


def _zaxis_rotation(axis: _Vector3) -> _Matrix3:
    """Construct a deterministic frame whose local z-axis is ``axis``."""

    z_axis = _normalise_vector(axis)
    if z_axis is None:
        return _IDENTITY_MATRIX

    # MuJoCo's zaxis shorthand specifies the local z direction and derives a
    # stable roll.  Use the shortest rotation from +z; this is equivalent for
    # the ordinary exported VLABench zaxis values and avoids an arbitrary
    # world-up choice near the poles.
    source = (0.0, 0.0, 1.0)
    cross = (
        source[1] * z_axis[2] - source[2] * z_axis[1],
        source[2] * z_axis[0] - source[0] * z_axis[2],
        source[0] * z_axis[1] - source[1] * z_axis[0],
    )
    dot = max(-1.0, min(1.0, sum(source[index] * z_axis[index] for index in range(3))))
    cross_norm = math.sqrt(sum(value * value for value in cross))
    if cross_norm <= 1e-12:
        if dot >= 0.0:
            return _IDENTITY_MATRIX
        return _axis_rotation("x", math.pi)
    # Quaternion for the shortest arc from source to target, in wxyz form.
    quaternion = [1.0 + dot, cross[0], cross[1], cross[2]]
    return _quat_rotation(quaternion)


def _compiler_angle_scale(root: ET.Element) -> float:
    compiler = root.find("./compiler")
    if compiler is not None and compiler.get("angle", "degree").lower() == "radian":
        return 1.0
    return math.pi / 180.0


def _compiler_euler_sequence(root: ET.Element) -> str:
    compiler = root.find("./compiler")
    sequence = "xyz" if compiler is None else compiler.get("eulerseq", "xyz")
    sequence = sequence.lower()
    if len(sequence) != 3 or any(axis not in "xyz" for axis in sequence):
        return "xyz"
    return sequence


def _parse_orientation(root: ET.Element, element: ET.Element) -> _Matrix3:
    """Read one MJCF orientation shorthand using MuJoCo's conventions."""

    def values_for(attribute: str) -> list[float] | None:
        value = element.get(attribute)
        if not value:
            return None
        try:
            return [float(part) for part in value.replace(",", " ").split()]
        except ValueError:
            return None

    values = values_for("quat")
    if values is not None:
        return _quat_rotation(values)

    values = values_for("axisangle")
    if values is not None and len(values) >= 4:
        axis = _normalise_vector((values[0], values[1], values[2]))
        if axis is not None:
            x, y, z = axis
            angle = values[3] * _compiler_angle_scale(root)
            cosine = math.cos(angle)
            sine = math.sin(angle)
            one_minus_cosine = 1.0 - cosine
            return (
                (
                    cosine + x * x * one_minus_cosine,
                    x * y * one_minus_cosine - z * sine,
                    x * z * one_minus_cosine + y * sine,
                ),
                (
                    y * x * one_minus_cosine + z * sine,
                    cosine + y * y * one_minus_cosine,
                    y * z * one_minus_cosine - x * sine,
                ),
                (
                    z * x * one_minus_cosine - y * sine,
                    z * y * one_minus_cosine + x * sine,
                    cosine + z * z * one_minus_cosine,
                ),
            )

    values = values_for("euler")
    if values is not None and len(values) >= 3:
        result = _IDENTITY_MATRIX
        scale = _compiler_angle_scale(root)
        for axis, angle in zip(_compiler_euler_sequence(root), values[:3]):
            result = _matrix_multiply(result, _axis_rotation(axis, angle * scale))
        return result

    values = values_for("xyaxes")
    if values is not None and len(values) >= 6:
        x_axis = _normalise_vector((values[0], values[1], values[2]))
        if x_axis is not None:
            raw_y = (values[3], values[4], values[5])
            projection = sum(raw_y[index] * x_axis[index] for index in range(3))
            orthogonal_y = tuple(
                raw_y[index] - projection * x_axis[index] for index in range(3)
            )
            y_axis = _normalise_vector(orthogonal_y)
            if y_axis is not None:
                z_axis = (
                    x_axis[1] * y_axis[2] - x_axis[2] * y_axis[1],
                    x_axis[2] * y_axis[0] - x_axis[0] * y_axis[2],
                    x_axis[0] * y_axis[1] - x_axis[1] * y_axis[0],
                )
                return (
                    (x_axis[0], y_axis[0], z_axis[0]),
                    (x_axis[1], y_axis[1], z_axis[1]),
                    (x_axis[2], y_axis[2], z_axis[2]),
                )

    values = values_for("zaxis")
    if values is not None and len(values) >= 3:
        return _zaxis_rotation((values[0], values[1], values[2]))
    return _IDENTITY_MATRIX


def _element_transform(root: ET.Element, element: ET.Element) -> _Transform:
    return _parse_orientation(root, element), _vec3(element.get("pos"))


def _set_element_pos(element: ET.Element, position: _Vector3) -> None:
    element.set("pos", " ".join(f"{value:.8g}" for value in position))


def _obj_bounds(path: Path) -> tuple[tuple[float, float, float], tuple[float, float, float]] | None:
    """Read lightweight ASCII OBJ vertex bounds when available."""

    lower = [float("inf")] * 3
    upper = [float("-inf")] * 3
    try:
        with path.open("r", encoding="utf-8", errors="ignore") as handle:
            for line in handle:
                if not line.startswith("v "):
                    continue
                values = line.split()
                if len(values) < 4:
                    continue
                try:
                    vertex = [float(values[index]) for index in range(1, 4)]
                except ValueError:
                    continue
                for index in range(3):
                    lower[index] = min(lower[index], vertex[index])
                    upper[index] = max(upper[index], vertex[index])
    except OSError:
        return None
    if any(value == float("inf") for value in lower):
        return None
    return tuple(lower), tuple(upper)


def _estimate_geom_bounds(root: ET.Element) -> tuple[tuple[float, float, float], tuple[float, float, float]]:
    """Estimate local bounds for offset sites when an asset omits them.

    Mesh extents are intentionally not guessed from binary files.  Primitive
    extents are enough for the common VLABench fixtures.  Every body and geom
    transform is composed before the bounds are accumulated, so this fallback
    does not silently turn an exported euler / quaternion pose into a pure
    translation estimate.
    """

    lower = [float("inf")] * 3
    upper = [float("-inf")] * 3
    mesh_bounds: dict[str, tuple[tuple[float, float, float], tuple[float, float, float]] | None] = {}
    asset = root.find("asset")
    if asset is not None:
        for mesh in asset.findall("mesh"):
            name = mesh.get("name")
            file_value = mesh.get("file")
            if not name or not file_value or not file_value.lower().endswith(".obj"):
                continue
            bounds = _obj_bounds(Path(file_value))
            if bounds is None:
                continue
            scale = _vec3(mesh.get("scale"), (1.0, 1.0, 1.0))
            scaled_values = [
                (bounds[0][index] * scale[index], bounds[1][index] * scale[index])
                for index in range(3)
            ]
            scaled_lower = tuple(min(values) for values in scaled_values)
            scaled_upper = tuple(max(values) for values in scaled_values)
            mesh_bounds[name] = (scaled_lower, scaled_upper)

    defaults = _default_geom_attributes(root)

    def include_point(point: _Vector3) -> None:
        for index in range(3):
            lower[index] = min(lower[index], point[index])
            upper[index] = max(upper[index], point[index])

    def include_box(transform: _Transform, extent: _Vector3) -> None:
        """Include a local axis-aligned box after its complete rotation."""

        rotation, center = transform
        world_extent = tuple(
            sum(abs(rotation[row][column]) * extent[column] for column in range(3))
            for row in range(3)
        )
        include_point(tuple(center[index] - world_extent[index] for index in range(3)))
        include_point(tuple(center[index] + world_extent[index] for index in range(3)))

    def include_mesh(transform: _Transform, bounds: tuple[_Vector3, _Vector3]) -> None:
        for x in bounds[0][0], bounds[1][0]:
            for y in bounds[0][1], bounds[1][1]:
                for z in bounds[0][2], bounds[1][2]:
                    include_point(_transform_point(transform, (x, y, z)))

    def visit(element: ET.Element, parent_transform: _Transform) -> None:
        transform = parent_transform
        if element.tag == "body":
            transform = _compose_transform(
                parent_transform, _element_transform(root, element)
            )
        if element.tag == "geom":
            geom_transform = _compose_transform(
                parent_transform, _element_transform(root, element)
            )
            geom_type = _effective_geom_attribute(element, "type", defaults) or "box"
            size_values: list[float] = []
            try:
                size_value = _effective_geom_attribute(element, "size", defaults) or ""
                size_values = [float(part) for part in size_value.replace(",", " ").split()]
            except ValueError:
                size_values = []
            size = tuple((size_values + [0.0, 0.0, 0.0])[:3])
            if geom_type == "sphere":
                extent = (size[0], size[0], size[0])
            elif geom_type in {"cylinder", "capsule"}:
                radius = size_values[0] if size_values else 0.0
                half_length = size_values[1] if len(size_values) > 1 else radius
                extent = (radius, radius, radius + half_length if geom_type == "capsule" else half_length)
            elif geom_type == "box":
                extent = size
            elif geom_type == "mesh" and element.get("mesh") in mesh_bounds:
                include_mesh(geom_transform, mesh_bounds[element.get("mesh", "")])
                extent = None
            else:
                # Binary .msh and unsupported mesh formats do not expose
                # vertices here; retaining their origin is safer than
                # inventing a large placement offset.
                extent = (0.0, 0.0, 0.0)
            if extent is not None:
                include_box(geom_transform, extent)
        for child in element:
            visit(child, transform)

    worldbody = root.find("worldbody")
    if worldbody is not None:
        visit(worldbody, (_IDENTITY_MATRIX, (0.0, 0.0, 0.0)))
    if any(value == float("inf") for value in lower):
        return (0.0, 0.0, 0.0), (0.0, 0.0, 0.0)
    return tuple(lower), tuple(upper)


def _make_offset_site(name: str, pos: tuple[float, float, float]) -> ET.Element:
    return ET.Element(
        "site",
        {
            "name": name,
            "pos": " ".join(f"{value:.8g}" for value in pos),
            "size": "0.005",
            "rgba": "0 0 0 0",
        },
    )


def _collect_placement_sites(
    root: ET.Element,
    placement_site_names: set[str],
) -> dict[str, ET.Element]:
    """Copy one source placement site per name into the world frame.

    ``MujocoXMLObject`` looks up its three offset sites directly below the
    adapter's outer body.  Moving a nested site without first applying every
    ancestor body transform changes its meaning.  Collecting the sites before
    restructuring the worldbody lets the adapter retain their source
    attributes while making the position explicit in the outer frame.
    """

    worldbody = root.find("worldbody")
    if worldbody is None:
        return {}
    sites: dict[str, ET.Element] = {}

    def visit(element: ET.Element, parent_transform: _Transform) -> None:
        transform = parent_transform
        if element.tag == "body":
            transform = _compose_transform(
                parent_transform, _element_transform(root, element)
            )
        if element.tag == "site":
            name = element.get("name")
            if name in placement_site_names and name not in sites:
                site = copy.deepcopy(element)
                _set_element_pos(
                    site, _transform_point(transform, _vec3(element.get("pos")))
                )
                sites[name] = site
        for child in element:
            visit(child, transform)

    visit(worldbody, (_IDENTITY_MATRIX, (0.0, 0.0, 0.0)))
    return sites


def _remove_placement_sites(root: ET.Element, placement_site_names: set[str]) -> None:
    """Remove all source copies after one transformed copy was collected."""

    worldbody = root.find("worldbody")
    if worldbody is None:
        return

    def visit(parent: ET.Element) -> None:
        for child in list(parent):
            if child.tag == "site" and child.get("name") in placement_site_names:
                parent.remove(child)
            else:
                visit(child)

    visit(worldbody)


def _make_object_wrapper(root: ET.Element) -> None:
    """Normalize worldbody to robosuite's outer-body/inner-object contract."""

    placement_site_names = {
        "bottom_site",
        "top_site",
        "horizontal_radius_site",
    }
    worldbody = root.find("worldbody")
    if worldbody is None:
        worldbody = ET.SubElement(root, "worldbody")

    # Capture the source sites before moving bodies.  The source may put the
    # conventional sites below an euler / quaternion body (or several nested
    # bodies), and duplicate names are common in generated VLABench XML.
    preserved_sites = _collect_placement_sites(root, placement_site_names)
    _remove_placement_sites(root, placement_site_names)

    direct_bodies = list(worldbody.findall("./body"))
    already_compatible = (
        len(direct_bodies) == 1
        and direct_bodies[0].find("./body[@name='object']") is not None
        and not [child for child in worldbody if child.tag not in {"body", "site"}]
    )
    outer_transform: _Transform = (_IDENTITY_MATRIX, (0.0, 0.0, 0.0))
    if already_compatible:
        outer = direct_bodies[0]
        outer_transform = _element_transform(root, outer)
    else:
        original_children = list(worldbody)
        for child in original_children:
            worldbody.remove(child)

        outer = ET.Element("body")
        inner = None
        # Preserve a single meaningful root body's pose instead of creating
        # an unnecessary third hierarchy level.
        if (
            len(direct_bodies) == 1
            and all(child.tag in {"body", "site"} for child in original_children)
        ):
            inner = direct_bodies[0]
            inner.set("name", "object")
            # Non-offset sites belong to the object subtree and must be
            # merged with it; only the three placement sites remain on the
            # outer body for MujocoXMLObject's offset properties.
            for child in original_children:
                if child.tag == "site" and child.get("name") not in placement_site_names:
                    inner.append(child)
        else:
            inner = ET.Element("body", {"name": "object"})
            for child in original_children:
                if child.tag == "site" and child.get("name") in placement_site_names:
                    continue
                inner.append(child)
        outer.append(inner)
        worldbody.append(outer)

    # LIBERO's offset properties expect these three sites on the outer body.
    # Source coordinates were collected in the world frame, so convert them
    # into the outer body's local frame before attaching the copies.  The
    # identity outer created above leaves ordinary one-body assets unchanged;
    # this inverse is relevant for an already-compatible source wrapper whose
    # outer body itself carries a pose.
    for name in ("bottom_site", "top_site", "horizontal_radius_site"):
        site = preserved_sites.get(name)
        if site is None:
            continue
        source_world_position = _vec3(site.get("pos"))
        _set_element_pos(
            site, _inverse_transform_point(outer_transform, source_world_position)
        )
        outer.append(site)

    # Several upstream fixtures intentionally omit placement sites.  Estimate
    # offsets from transformed primitive / ASCII-mesh bounds so a container
    # does not start half below the table.  The estimate is still a fallback;
    # source placement sites above always win and are never duplicated.
    lower, upper = _estimate_geom_bounds(root)
    center_xy = ((lower[0] + upper[0]) / 2, (lower[1] + upper[1]) / 2)
    estimated_world_sites = {
        "bottom_site": (center_xy[0], center_xy[1], lower[2]),
        "top_site": (center_xy[0], center_xy[1], upper[2]),
        "horizontal_radius_site": (
            max(abs(lower[0] - center_xy[0]), abs(upper[0] - center_xy[0]), abs(lower[1] - center_xy[1]), abs(upper[1] - center_xy[1])),
            0.0,
            0.0,
        ),
    }
    existing = {site.get("name") for site in outer.findall("./site")}
    for name in ("bottom_site", "top_site", "horizontal_radius_site"):
        if name not in existing:
            estimated_local = _inverse_transform_point(
                outer_transform, estimated_world_sites[name]
            )
            outer.append(_make_offset_site(name, estimated_local))


def _cache_path_for_source(
    source: Path,
    cache_dir: Path,
    *,
    source_bytes: bytes | None = None,
    ensure_dynamic_mass: bool = False,
    repair_static_bodies: bool = False,
    visual_tag: str | None = None,
    visual_rgba: Iterable[float] | None = None,
) -> Path:
    """Return a cache path unique to source identity and converter schema.

    Generated XML embeds absolute resource paths.  Content-only addressing
    would therefore incorrectly share an adapter between two roots that have
    byte-identical XML but different mesh / texture locations.
    """

    if source_bytes is None:
        source_bytes = source.read_bytes()
    digest_input = b"\0".join(
        (
            VLABENCH_CONVERTER_SCHEMA_VERSION.encode("utf-8"),
            os.fsencode(str(source.resolve())),
            f"ensure_dynamic_mass={int(ensure_dynamic_mass)}".encode("ascii"),
            f"repair_static_bodies={int(repair_static_bodies)}".encode("ascii"),
            f"visual_tag={visual_tag or ''}".encode("utf-8"),
            f"visual_rgba={tuple(float(value) for value in visual_rgba) if visual_rgba is not None else ''}".encode("utf-8"),
            source_bytes,
        )
    )
    digest = hashlib.sha256(digest_input).hexdigest()[:20]
    return cache_dir / f"{source.stem}-{digest}.xml"


def _default_adapter_cache_dir() -> Path:
    """Return a private, user-scoped cache directory in the system temp dir."""

    get_uid = getattr(os, "getuid", None)
    if callable(get_uid):
        user_token = str(get_uid())
    else:
        try:
            username = getpass.getuser()
        except (KeyError, OSError):
            username = "unknown"
        user_token = re.sub(r"[^A-Za-z0-9_.-]+", "_", username) or "unknown"
    return Path(tempfile.gettempdir()) / f"libero-vlabench-adapter-{user_token}"


def _atomic_write_tree(tree: ET.ElementTree, destination: Path) -> None:
    """Serialize an XML tree and atomically publish it at ``destination``.

    The temporary file lives beside the destination, making ``os.replace`` a
    same-filesystem atomic publication.  A failed serialization removes the
    temporary file and leaves any previous complete destination untouched.
    """

    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary: Path | None = None
    file_descriptor: int | None = None
    try:
        file_descriptor, temporary_name = tempfile.mkstemp(
            prefix=f".{destination.name}.",
            suffix=".tmp",
            dir=str(destination.parent),
        )
        temporary = Path(temporary_name)
        with os.fdopen(file_descriptor, "wb") as handle:
            file_descriptor = None
            tree.write(handle, encoding="utf-8", xml_declaration=True)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, destination)
        temporary = None
    finally:
        if file_descriptor is not None:
            os.close(file_descriptor)
        if temporary is not None:
            try:
                temporary.unlink()
            except FileNotFoundError:
                pass


def _indent_xml(tree: ET.ElementTree) -> None:
    """Pretty-print an XML tree on Python versions before ``ET.indent``.

    LIBERO's supported environment still includes Python 3.8, where the
    stdlib helper introduced in 3.9 is unavailable.  Formatting is not part
    of the adapter contract, but keeping generated files readable is useful
    when auditing a converted asset.
    """

    indent = getattr(ET, "indent", None)
    if indent is not None:
        indent(tree, space="  ")
        return

    def visit(element: ET.Element, level: int) -> None:
        children = list(element)
        if children:
            if not element.text or not element.text.strip():
                element.text = "\n" + "  " * (level + 1)
            for child in children:
                visit(child, level + 1)
                if not child.tail or not child.tail.strip():
                    child.tail = "\n" + "  " * (level + 1)
            if not children[-1].tail or not children[-1].tail.strip():
                children[-1].tail = "\n" + "  " * level
        elif level and (not element.tail or not element.tail.strip()):
            element.tail = "\n" + "  " * level

    root = tree.getroot()
    if root is not None:
        visit(root, 0)


def convert_vlabench_xml(
    xml_path: str | os.PathLike[str],
    destination: str | os.PathLike[str] | None = None,
    *,
    ensure_dynamic_mass: bool = False,
    repair_static_bodies: bool = False,
    visual_tag: str | None = None,
    visual_rgba: Iterable[float] | None = None,
) -> Path:
    """Create a LIBERO-compatible adapter XML for one external asset.

    The generated XML is small and contains absolute references to the
    original external mesh/texture files.  ``destination`` is useful for
    tests or inspection; without it a source- and schema-addressed temporary
    cache is used.  Source mass / density attributes are preserved exactly by
    default.  ``ensure_dynamic_mass`` is an explicit runtime-object opt-in:
    it repairs only a concrete geom in a body that has a joint (or the
    movable object root) when the source/default-expanded collision mass is
    zero.  Static fixture bodies and default templates are never rewritten
    unless ``repair_static_bodies`` is also explicitly enabled by a fixture
    wrapper; even then, only concrete collision geoms receive the minimum
    repair.

    ``visual_tag`` optionally adds VLABench's ordinary ingredient package
    label (currently ``sugar``, ``salt``, or ``hotsauce``) to the selected
    condiment.  It is a pair of back-to-back visual-only mesh geoms using the
    same print/material and does not change the object's state contract.
    ``visual_rgba`` is a visual-only solution colour override for the pinned
    ChemistryTube mesh.
    """

    source = Path(xml_path).expanduser().resolve()
    if not source.is_file():
        raise VLABenchAssetsUnavailable(f"VLABench XML does not exist: {source}")

    try:
        source_bytes = source.read_bytes()
        source_root = ET.fromstring(source_bytes)
    except ET.ParseError as exc:
        raise VLABenchAssetError(f"Unable to parse VLABench XML {source}: {exc}") from exc
    root = copy.deepcopy(source_root)
    _flatten_nested_default_classes(root)
    _normalise_geom_groups(root)
    _absolutise_asset_files(root, source.parent)
    _add_visual_tag(root, source, visual_tag)
    _set_visual_rgba(root, visual_rgba)
    _remove_unreferenced_mesh_assets(root)
    _ensure_named_meshes(root)
    _ensure_named_sites_and_joints(root)
    _ensure_named_geoms(root)
    _make_object_wrapper(root)
    # MuJoCo 3.x requires ranged joints to opt into limits explicitly when
    # the source XML predates ``autolimits``.  This is a compiler compatibility
    # attribute only; it does not alter any range, mass, friction, or contact
    # parameter from the external asset.
    compiler = root.find("compiler")
    if compiler is None:
        compiler = ET.Element("compiler")
        root.insert(0, compiler)
    compiler.set("autolimits", "true")
    if ensure_dynamic_mass:
        _ensure_positive_dynamic_body_mass(
            root,
            include_static_bodies=repair_static_bodies,
        )
    root.append(ET.Comment(
        " LIBERO adapter generated at runtime; source asset remains external and is not redistributed. "
        f"VLABench assets revision {VLABENCH_ASSET_REVISION}. "
    ))

    if destination is None:
        cache_value = os.environ.get(VLABENCH_ADAPTER_CACHE_ENV)
        if cache_value:
            cache_dir = Path(cache_value).expanduser()
        else:
            cache_dir = _default_adapter_cache_dir()
        cache_dir.mkdir(parents=True, exist_ok=True, mode=0o700)
        if not cache_value:
            # ``mode`` is ignored when a path already exists.  This cache is
            # generated data, so tighten permissions for the user-scoped
            # default without imposing policy on an explicit override.
            try:
                cache_dir.chmod(0o700)
            except OSError:
                pass
        destination_path = _cache_path_for_source(
            source,
            cache_dir,
            source_bytes=source_bytes,
            ensure_dynamic_mass=ensure_dynamic_mass,
            repair_static_bodies=repair_static_bodies,
            visual_tag=visual_tag,
            visual_rgba=visual_rgba,
        )
    else:
        destination_path = Path(destination).expanduser().resolve()
        destination_path.parent.mkdir(parents=True, exist_ok=True)

    tree = ET.ElementTree(root)
    _indent_xml(tree)
    _atomic_write_tree(tree, destination_path)
    return destination_path


def resolve_vlabench_object_xml(
    key: str,
    root: str | os.PathLike[str] | None = None,
    *,
    allow_primitive_fallback: bool = False,
    ensure_dynamic_mass: bool = False,
    repair_static_bodies: bool = False,
    visual_tag: str | None = None,
    visual_rgba: Iterable[float] | None = None,
    manifest_path: str | os.PathLike[str] | None = None,
) -> tuple[Path, bool]:
    """Resolve and convert an object, returning ``(xml_path, is_fallback)``."""

    external = resolve_vlabench_asset(
        key, root, require=False, manifest_path=manifest_path
    )
    if external is not None:
        missing = validate_vlabench_xml_resources(external)
        if not missing:
            return (
                convert_vlabench_xml(
                    external,
                    ensure_dynamic_mass=ensure_dynamic_mass,
                    repair_static_bodies=repair_static_bodies,
                    visual_tag=visual_tag,
                    visual_rgba=visual_rgba,
                ),
                False,
            )
    if allow_primitive_fallback:
        # Primitive fallbacks are repository-owned, small clean-room
        # reconstructions.  The manifest names the fallback explicitly so a
        # wrapper can opt in without hard-coding a VLABench asset path here.
        # Keep the historical seesaw default for manifests created before
        # ``primitive_fallback`` was introduced.
        fallback_name = get_vlabench_asset_spec(
            key, manifest_path=manifest_path
        ).primitive_fallback
        if fallback_name is None and key.lower() == "seesaw":
            fallback_name = "seesaw_primitive.xml"
        if fallback_name:
            fallback_path = Path(fallback_name)
            if fallback_path.is_absolute() or ".." in fallback_path.parts:
                raise VLABenchManifestError(
                    f"Primitive fallback escapes package asset root: {fallback_name!r}"
                )
            fallback = (
                Path(__file__).resolve().parents[1]
                / "assets"
                / "external"
                / "vlabench"
                / fallback_path
            )
            if fallback.is_file():
                return fallback, True
    if external is None:
        raise VLABenchAssetsUnavailable(
            f"No downloaded XML for {key!r}; set {VLABENCH_ASSET_ROOT_ENV} or download "
            f"{VLABENCH_ASSET_REPOSITORY}@{VLABENCH_ASSET_REVISION}"
        )
    missing_text = ", ".join(str(path) for path in validate_vlabench_xml_resources(external))
    raise VLABenchAssetsUnavailable(
        f"VLABench asset {key!r} is incomplete ({missing_text}); "
        "download all XML-referenced files before loading it"
    )


__all__ = [
    "DEFAULT_VLABENCH_ASSET_ROOT",
    "VLABENCH_ADAPTER_CACHE_ENV",
    "VLABENCH_ASSET_REPOSITORY",
    "VLABENCH_ASSET_REVISION",
    "VLABENCH_ASSET_ROOT_ENV",
    "VLABENCH_CONVERTER_SCHEMA_VERSION",
    "VLABENCH_SOURCE_COMMIT",
    "VLABENCH_SOURCE_REPOSITORY",
    "VLABenchAssetError",
    "VLABenchAssetSpec",
    "VLABenchAssetsUnavailable",
    "VLABenchManifestError",
    "audit_vlabench_assets",
    "convert_vlabench_xml",
    "get_vlabench_asset_spec",
    "iter_vlabench_asset_specs",
    "load_vlabench_manifest",
    "referenced_vlabench_files",
    "resolve_vlabench_asset",
    "resolve_vlabench_asset_root",
    "resolve_vlabench_object_xml",
    "validate_vlabench_xml_resources",
]
